### ISSUE TITLE
please do not call curl_init() directly

### ISSUE THREAD

**Issue by danmarsden** [devlionco/moodle-local_lionai_reports#16]
Please don't initate curl_init() directly but use Moodle's own "curl" class which is a wrapper on PHP's curl functions.

This isn't documented well, but do a search on moodle core code for "curl" and you should see examples of it's use.

The wrapper function takes care of some security and proxy settings Moodle enforces.

**Comment by Uriel-Cerem-Devliom** [comment]
Hi @danmarsden , 

thanks for the advice about curl class/wrapper! fix taht on this commit (the link above).

**Comment by Uriel-Cerem-Devlion** [comment]
Hi @danmarsden , 

thanks for the advice about curl class/wrapper! fix taht on this commit (the link above).

**Comment by Uriel-Cerem-Devlion** [comment]
Hi @danmarsden , 

thanks for the advice about curl class/wrapper! fix taht on this commit (the link above).
