### ISSUE TITLE
invalid privacy api class

### ISSUE THREAD

**Issue by danmarsden** [devlionco/moodle-local_lionai_reports#17]
your plugin stores user data in a number of tables which will need to be included in the privacy api classes - the use of the null provider class is incorrect.
More information on the privacy class is here:
https://moodledev.io/docs/apis/subsystems/privacy# 

As your site integrates with an external API this is a blocker for plugins db approval. You will need to pay close attention to the part of the privacy api docs too:
https://moodledev.io/docs/apis/subsystems/privacy#indicating-that-you-export-data-to-an-external-location

Sites that use continuous integration processes will not be able to use your plugin because Moodle runs unit tests which check to see if all extra plugins include the privacy class.

**Comment by Uriel-Cerem-Devlion** [comment]
Hi @danmarsden , 

as far as I understand the privacy api, it is needed in case I export some personal data. However, the plugin does not do that, and just send a post request to api, providing only the moodle version, dbtype and a prompt (which is, obviously, a text). why does the null provider is not enough in this case (except the fact that I didn't added the string)? should the privacy api include details about the system info we send?

**Comment by danmarsden** [comment]
the table you define includes a "userid" field... so the data is associated with a user and needs to be covered by the privacy api:
https://github.com/devlionco/moodle-local_lionai_reports/blob/main/db/install.xml#L7-L15

Moodle also has some core unit tests that check for tables that include userid that are not covered by the privacy api class - so if someone installs your plugin in their site, then runs the core unit tests - they will fail - and if sites use CI processes to deploy code to their servers, that failing unit test will prevent them from being able to deploy it to their production site.

We don't block approval for stand-alone plugins on this basis, but for plugins that integrate with an external service (like yours does) this is a blocker for approval sorry!

**Comment by Uriel-Cerem-Devlion** [comment]
Hi @danmarsden , 

As you can see, we made a commit in a new branch that suppose to solve the issue of the privacy provider. The reasom I didn't merged it is that I would like you to take a look at the changes in the provider, and let me know is as it supposed to be. 

The logic - according to the Privacy API documentation, we should distinguish the cases in the provider between sending the information outside the system or not. Even though we interact with external API, we do not send any user data, as I mentioned above. Therefore, I fix the provider to use "add_database_table" rather than the "add_external_location_link" you sent in the first message in the thread. 
If there is something wrong with my understanding of the Privacy API, I would like to learn more from you about what I am missing here.

**Comment by danmarsden** [comment]
Hi Uriel, 

yes that's a good start in the branch here:
https://github.com/devlionco/moodle-local_lionai_reports/blob/issue_%2317/clasess/privacy/provider.php

but it's missing the export and delete apis that allow a user to request the deletion of the user data and also the request of the user data as covered in the privacy api docs - you can also look at some of the other core plugins to see good examples of plugins that handle the export and deletion processes.

If you don't want to implement the correct delete/export functions in the privacy api you migh" have done enough to pass the plugins db approval blocker, but I'd need to discuss that with the plugin review team to decide if we'd block approval on the incomplete privacy api class.

thanks!

**Comment by Uriel-Cerem-Devlion** [comment]
hi @danmarsden, 

Hopefully that I understood your comments about the privacy api, I added the delete and export api's. if there is anything wrong with them, let me know and I'll fix them, in order to make the approval as easy and fast as possible.
