### ISSUE TITLE
invalid use of the data manipulation api.

### ISSUE THREAD

**Issue by danmarsden** [devlionco/moodle-local_lionai_reports#18]
Your plugin documentation states that it allows admins to write natural language queries - but it fails to state that it also enables 
 admin users to write SQL statements and have them run directly on the server - but this is not clear in the documentation or README. - the getresult() function takes a PARAM_RAW value (which looks very strange and should probably be PARAM_TEXT at the very least.) but then passes it direclty into a get_recordset_sql() call.

NOTE: Moodle doesn't do any checking to see if the user has added something like a "DROP TABLE" or something malicious in that sql query - it's up to you to santise that before it's passed to the data manipulation api functions.

There are some other plugins like configurable_reports and report_customsql that allow this, but they also add some basic security checks to make it harder for malicious SQL queries to be run directly by the end user.

Ideally this should be documented clearly in your plugins db description and README files, but I think there's some improvements you can make there to decrease some of the risks.

**Comment by Uriel-Cerem-Devlion** [comment]
Hi @danmarsden , 
You are completely right! we were relying on the fact that our API is doing those checkings for the plugin (and which it does, we tested it's safety), but forgot to do the same in hte plugin itself. 

Can you take a look at the commit above to see it it is OK now? I took a look at configurable_reports to understand how they check and implement it lionai_reports. hopes that is closing the problem.
