### ISSUE TITLE
codemirror.js missing from thirdpartylibs.xml

### ISSUE THREAD

**Issue by danmarsden** [devlionco/moodle-local_lionai_reports#21]
the codemirror.js appears to be missing all it's licence and copyright info - it needs to be added to thirdpartylibs.xml file but it is also missing the MIT license statement.

if you look at the MIT license for codemirror it clearly states:

"The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software."

**Comment by Uriel-Cerem-Devlion** [comment]
hi @danmarsden , 

we added a reference to the licence and added codemirror to thirdpartylibs.xml, hopefully that now it is OK.
