### ISSUE TITLE
Missed validate_context() in some web service methods

### ISSUE THREAD

**Issue by volodymyrdovhan** [devlionco/moodle-local_lionai_reports#29]
Please review externallib.php.

In some methods missed context validation, which is required: https://moodledev.io/docs/4.5/apis/subsystems/external/writing-a-service#context-and-capability-checks

Thanks

**Comment by Uriel-Cerem-Devlion** [comment]
Thanks @volodymyrdovhan, 

I've pushed a fix for that.
